# Generated by Django 4.1.6 on 2023-07-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=50)),
                ('cname', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('img', models.FileField(default=None, null=True, upload_to='')),
                ('date', models.DateField()),
            ],
        ),
    ]
