# Generated by Django 4.1.6 on 2023-07-17 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0002_alter_audition_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audition',
            name='date',
        ),
    ]
