# Generated by Django 4.1.6 on 2023-07-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditionregistration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuditionRegistration',
            new_name='AuditionRegistrationModel',
        ),
    ]
