# Generated by Django 4.1.6 on 2023-07-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditionregistration', '0002_rename_auditionregistration_auditionregistrationmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditionregistrationmodel',
            old_name='img',
            new_name='regimg',
        ),
    ]
