# Generated by Django 4.1.6 on 2023-07-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditionregistration', '0003_rename_img_auditionregistrationmodel_regimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('nimg', models.FileField(default=None, max_length=255, null=True, upload_to='auditionregi/')),
            ],
        ),
        migrations.DeleteModel(
            name='AuditionRegistrationModel',
        ),
    ]
